services:
    agsr_test_db:
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: agsr_test_db
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=Password_123!
            - MSSQL_PID=Express
        ports:
            - "1433:1433"
        restart: always
        volumes:
            - agsr_test_data:/var/opt/mssql
 
    agsr_test_api:
        container_name: agsr_test_api
        ports:
            - 8080:8080
        build:
            context: ./AgsrTest.Api
            dockerfile: Dockerfile
        depends_on: 
            - "agsr_test_db"
        environment:
            - ConnectionStrings__DefaultConnection=Server=agsr_test_db;User ID=sa;Password=Password_123!;Database=mydb;Encrypt=False;
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8080/healthcheck"]
            interval: 10s
            timeout: 10s
            retries: 10

    agsr_test_console:
        container_name: agsr_test_console
        build:
            context: ./AgsrTest.ConsoleApp
            dockerfile: Dockerfile
        depends_on:
            agsr_test_api:
                condition: service_healthy
        entrypoint: ["sh", "-c", "while ! curl -s http://agsr_test_api:8080/healthcheck; do sleep 2; done; dotnet AgsrTest.ConsoleApp.dll"]
    
volumes:
    agsr_test_data: